# Based on https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
# optimization: https://github.com/marketplace/actions/skip-duplicate-actions#usage-examples

name: IDE PR build and tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review]

jobs:
  sbt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: sbt test
      run: sbt -v +test

  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking the code with scalafmt
        uses: AvaPL/scalafmt-native-formatter@v0
